"""Description:
    Verify context summarisation thresholds, persistence, and compaction behaviour.

Requirements:
    - Prove summarisation triggers when the configured message-count threshold is reached.
    - Prove summaries persist to and load from disk correctly.
    - Prove compaction keeps a recent message tail and persists the generated summary.
"""

from __future__ import annotations

import asyncio

from faith_pa.agent.base import AgentMessage
from faith_pa.agent.summariser import ContextSummariser


def test_should_summarise_on_message_count(tmp_path):
    """Description:
    Verify summarisation triggers when the configured maximum message count is reached.

    Requirements:
        - This test is needed to prove high-volume conversations trigger compaction before the context grows unchecked.
        - Verify the summariser returns ``True`` once the configured message cap is met.

    :param tmp_path: Temporary pytest directory fixture.
    """

    summariser = ContextSummariser(
        agent_id="dev",
        model_name="gpt-5.4",
        context_window_tokens=1000,
        context_config={"summary_threshold_pct": 90, "max_messages": 2},
        faith_dir=tmp_path,
    )
    messages = [{"role": "user", "content": "one"}, {"role": "assistant", "content": "two"}]
    assert summariser.should_summarise(messages) is True


def test_persist_and_load_summary_roundtrip(tmp_path):
    """Description:
    Verify persisted summaries can be loaded back from the agent context file.

    Requirements:
        - This test is needed to prove rolling summaries survive across runtime restarts.
        - Verify the summary file is created and the original summary text is returned.

    :param tmp_path: Temporary pytest directory fixture.
    """

    summariser = ContextSummariser(
        agent_id="dev",
        model_name="gpt-5.4",
        context_window_tokens=1000,
        faith_dir=tmp_path,
    )
    summariser.persist_summary("Important summary")
    assert summariser.context_md_path.exists()
    assert summariser.load_summary() == "Important summary"


def test_compact_retains_recent_messages_and_compacts_disposable(tmp_path):
    """Description:
    Verify compaction retains recent non-disposable messages and summarises older history.

    Requirements:
        - This test is needed to prove history compaction preserves recent conversational context.
        - Verify disposable and older messages are summarised and a synthetic compaction marker is inserted.

    :param tmp_path: Temporary pytest directory fixture.
    """

    summariser = ContextSummariser(
        agent_id="dev",
        model_name="gpt-5.4",
        context_window_tokens=1000,
        faith_dir=tmp_path,
        retain_recent_messages=2,
    )

    messages = [
        AgentMessage(role="user", content="old-1"),
        AgentMessage(role="assistant", content="old-2", disposable=True),
        AgentMessage(role="user", content="keep-1"),
        AgentMessage(role="assistant", content="keep-2"),
    ]

    async def fake_llm(prompt: str) -> str:
        """Description:
            Return a deterministic summary for the compaction test.

        Requirements:
            - Assert that both old and retained messages are present in the generated prompt.

        :param prompt: Summary prompt generated by the summariser.
        :returns: Deterministic summary text.
        """

        assert "old-1" in prompt
        assert "keep-2" in prompt
        return "Summarised context"

    result = asyncio.run(summariser.compact(messages, existing_summary="", llm_call=fake_llm))

    assert result.summary == "Summarised context"
    assert result.compacted_messages >= 2
    assert result.remaining_messages[0]["role"] == "system"
    assert [item["content"] for item in result.remaining_messages[1:]] == ["keep-1", "keep-2"]
    assert summariser.load_summary() == "Summarised context"
